var q=!0,r=null,t=!1;function w(){this.b=1;this.c=4;this.l=0.5;this.j=1E3;this.m=0.5;this.n=4;this.k=32}
w.prototype.a=function(f,b,a,d){"undefined"==typeof d&&(d=0>=this.b?Number.MAX_VALUE:(new Date).getTime()+1E3*this.b);if(f==r||b==r)throw Error("Null input. (diff_main)");if(f==b)return f?[[0,f]]:[];"undefined"==typeof a&&(a=q);var h=a,c=A(f,b);a=f.substring(0,c);f=f.substring(c);b=b.substring(c);var c=B(f,b),e=f.substring(f.length-c);f=f.substring(0,f.length-c);b=b.substring(0,b.length-c);f=D(this,f,b,h,d);a&&f.unshift([0,a]);e&&f.push([0,e]);H(this,f);return f};
function D(f,b,a,d,h){if(!b)return[[1,a]];if(!a)return[[-1,b]];var c=b.length>a.length?b:a,e=b.length>a.length?a:b,g=c.indexOf(e);if(-1!=g)return f=[[1,c.substring(0,g)],[0,e],[1,c.substring(g+e.length)]],b.length>a.length&&(f[0][0]=f[2][0]=-1),f;if(1==e.length)return[[-1,b],[1,a]];e=function(a,b,c){for(var d=a.substring(c,c+Math.floor(a.length/4)),e=-1,f="",g,h,j,k;-1!=(e=b.indexOf(d,e+1));){var l=A(a.substring(c),b.substring(e)),m=B(a.substring(0,c),b.substring(0,e));f.length<m+l&&(f=b.substring(e-
m,e)+b.substring(e,e+l),g=a.substring(0,c-m),h=a.substring(c+l),j=b.substring(0,e-m),k=b.substring(e+l))}return 2*f.length>=a.length?[g,h,j,k,f]:r};if(0>=f.b)c=r;else{var g=b.length>a.length?b:a,j=b.length>a.length?a:b;if(4>g.length||2*j.length<g.length)c=r;else if(c=e(g,j,Math.ceil(g.length/4)),e=e(g,j,Math.ceil(g.length/2)),!c&&!e)c=r;else{var c=e?c?c[4].length>e[4].length?c:e:e:c,k;b.length>a.length?(e=c[0],g=c[1],j=c[2],k=c[3]):(j=c[0],k=c[1],e=c[2],g=c[3]);c=[e,g,j,k,c[4]]}}if(c)return b=c[1],
e=c[3],a=c[4],c=f.a(c[0],c[2],d,h),f=f.a(b,e,d,h),c.concat([[0,a]],f);if(d&&100<b.length&&100<a.length){d=function(a){for(var b="",c=0,d=-1,e=C.length;d<a.length-1;){d=a.indexOf("\n",c);-1==d&&(d=a.length-1);var f=a.substring(c,d+1),c=d+1;(z.hasOwnProperty?z.hasOwnProperty(f):void 0!==z[f])?b+=String.fromCharCode(z[f]):(b+=String.fromCharCode(e),z[f]=e,C[e++]=f)}return b};var C=[],z={};C[0]="";b=d(b);a=d(a);d={d:b,e:a,i:C};a=d.d;c=d.e;b=d.i;a=f.a(a,c,t,h);for(d=0;d<a.length;d++){c=a[d][1];e=[];for(g=
0;g<c.length;g++)e[g]=b[c.charCodeAt(g)];a[d][1]=e.join("")}d=t;for(var c=[],e=0,g=r,m=k=j=b=0,s=0;b<a.length;)0==a[b][0]?(c[e++]=b,j=m,k=s,s=m=0,g=a[b][1]):(1==a[b][0]?m+=a[b][1].length:s+=a[b][1].length,g&&(g.length<=Math.max(j,k)&&g.length<=Math.max(m,s))&&(a.splice(c[e-1],0,[-1,g]),a[c[e-1]+1][0]=1,e--,e--,b=0<e?c[e-1]:-1,s=m=k=j=0,g=r,d=q)),b++;d&&H(f,a);b=function(a,b){if(!a||!b)return 6;var c=a.charAt(a.length-1),d=b.charAt(0),e=c.match(I),f=d.match(I),g=e&&c.match(J),h=f&&d.match(J),c=g&&
c.match(K),d=h&&d.match(K),j=c&&a.match(L),k=d&&b.match(M);return j||k?5:c||d?4:e&&!g&&h?3:g||h?2:e||f?1:0};for(d=1;d<a.length-1;){if(0==a[d-1][0]&&0==a[d+1][0]){c=a[d-1][1];e=a[d][1];g=a[d+1][1];if(j=B(c,e))k=e.substring(e.length-j),c=c.substring(0,c.length-j),e=k+e.substring(0,e.length-j),g=k+g;j=c;k=e;m=g;for(s=b(c,e)+b(e,g);e.charAt(0)===g.charAt(0);){var c=c+e.charAt(0),e=e.substring(1)+g.charAt(0),g=g.substring(1),y=b(c,e)+b(e,g);y>=s&&(s=y,j=c,k=e,m=g)}a[d-1][1]!=j&&(j?a[d-1][1]=j:(a.splice(d-
1,1),d--),a[d][1]=k,m?a[d+1][1]=m:(a.splice(d+1,1),d--))}d++}for(b=1;b<a.length;){if(-1==a[b-1][0]&&1==a[b][0]){d=a[b-1][1];c=a[b][1];e=N(d,c);g=N(c,d);if(e>=g){if(e>=d.length/2||e>=c.length/2)a.splice(b,0,[0,c.substring(0,e)]),a[b-1][1]=d.substring(0,d.length-e),a[b+1][1]=c.substring(e),b++}else if(g>=d.length/2||g>=c.length/2)a.splice(b,0,[0,d.substring(0,g)]),a[b-1][0]=1,a[b-1][1]=c.substring(0,c.length-g),a[b+1][0]=-1,a[b+1][1]=d.substring(g),b++;b++}b++}a.push([0,""]);c=d=b=0;for(g=e="";b<a.length;){switch(a[b][0]){case 1:c++;
g+=a[b][1];break;case -1:d++;e+=a[b][1];break;case 0:if(1<=d&&1<=c){a.splice(b-d-c,d+c);b=b-d-c;d=f.a(e,g,t,h);for(c=d.length-1;0<=c;c--)a.splice(b,0,d[c]);b+=d.length}d=c=0;g=e=""}b++}a.pop();f=a}else a:{d=b.length;c=a.length;e=Math.ceil((d+c)/2);g=2*e;j=Array(g);k=Array(g);for(m=0;m<g;m++)j[m]=-1,k[m]=-1;j[e+1]=0;k[e+1]=0;for(var m=d-c,s=0!=m%2,E=y=0,F=0,G=0,v=0;v<e&&!((new Date).getTime()>h);v++){for(var p=-v+y;p<=v-E;p+=2){var l=e+p,n;n=p==-v||p!=v&&j[l-1]<j[l+1]?j[l+1]:j[l-1]+1;for(var x=n-p;n<
d&&x<c&&b.charAt(n)==a.charAt(x);)n++,x++;j[l]=n;if(n>d)E+=2;else if(x>c)y+=2;else if(s&&(l=e+m-p,0<=l&&l<g&&-1!=k[l])){var u=d-k[l];if(n>=u){f=O(f,b,a,n,x,h);break a}}}for(p=-v+F;p<=v-G;p+=2){l=e+p;u=p==-v||p!=v&&k[l-1]<k[l+1]?k[l+1]:k[l-1]+1;for(n=u-p;u<d&&n<c&&b.charAt(d-u-1)==a.charAt(c-n-1);)u++,n++;k[l]=u;if(u>d)G+=2;else if(n>c)F+=2;else if(!s&&(l=e+m-p,0<=l&&(l<g&&-1!=j[l])&&(n=j[l],x=e+n-l,u=d-u,n>=u))){f=O(f,b,a,n,x,h);break a}}}f=[[-1,b],[1,a]]}return f}
function O(f,b,a,d,h,c){var e=b.substring(d),g=a.substring(h);b=f.a(b.substring(0,d),a.substring(0,h),t,c);f=f.a(e,g,t,c);return b.concat(f)}function A(f,b){if(!f||!b||f.charAt(0)!=b.charAt(0))return 0;for(var a=0,d=Math.min(f.length,b.length),h=d,c=0;a<h;)f.substring(c,h)==b.substring(c,h)?c=a=h:d=h,h=Math.floor((d-a)/2+a);return h}
function B(f,b){if(!f||!b||f.charAt(f.length-1)!=b.charAt(b.length-1))return 0;for(var a=0,d=Math.min(f.length,b.length),h=d,c=0;a<h;)f.substring(f.length-h,f.length-c)==b.substring(b.length-h,b.length-c)?c=a=h:d=h,h=Math.floor((d-a)/2+a);return h}
function N(f,b){var a=f.length,d=b.length;if(0==a||0==d)return 0;a>d?f=f.substring(a-d):a<d&&(b=b.substring(0,a));a=Math.min(a,d);if(f==b)return a;for(var d=0,h=1;;){var c=b.indexOf(f.substring(a-h));if(-1==c)return d;h+=c;if(0==c||f.substring(a-h)==b.substring(0,h))d=h,h++}}var I=/[^a-zA-Z0-9]/,J=/\s/,K=/[\r\n]/,L=/\n\r?\n$/,M=/^\r?\n\r?\n/;
w.prototype.f=function(f){for(var b=t,a=[],d=0,h=r,c=0,e=t,g=t,j=t,k=t;c<f.length;){if(0==f[c][0])f[c][1].length<this.c&&(j||k)?(a[d++]=c,e=j,g=k,h=f[c][1]):(d=0,h=r),j=k=t;else if(-1==f[c][0]?k=q:j=q,h&&(e&&g&&j&&k||h.length<this.c/2&&3==e+g+j+k))f.splice(a[d-1],0,[-1,h]),f[a[d-1]+1][0]=1,d--,h=r,e&&g?(j=k=q,d=0):(d--,c=0<d?a[d-1]:-1,j=k=t),b=q;c++}b&&H(this,f)};
function H(f,b){b.push([0,""]);for(var a=0,d=0,h=0,c="",e="",g;a<b.length;)switch(b[a][0]){case 1:h++;e+=b[a][1];a++;break;case -1:d++;c+=b[a][1];a++;break;case 0:1<d+h?(0!==d&&0!==h&&(g=A(e,c),0!==g&&(0<a-d-h&&0==b[a-d-h-1][0]?b[a-d-h-1][1]+=e.substring(0,g):(b.splice(0,0,[0,e.substring(0,g)]),a++),e=e.substring(g),c=c.substring(g)),g=B(e,c),0!==g&&(b[a][1]=e.substring(e.length-g)+b[a][1],e=e.substring(0,e.length-g),c=c.substring(0,c.length-g))),0===d?b.splice(a-h,d+h,[1,e]):0===h?b.splice(a-d,d+
h,[-1,c]):b.splice(a-d-h,d+h,[-1,c],[1,e]),a=a-d-h+(d?1:0)+(h?1:0)+1):0!==a&&0==b[a-1][0]?(b[a-1][1]+=b[a][1],b.splice(a,1)):a++,d=h=0,e=c=""}""===b[b.length-1][1]&&b.pop();d=t;for(a=1;a<b.length-1;)0==b[a-1][0]&&0==b[a+1][0]&&(b[a][1].substring(b[a][1].length-b[a-1][1].length)==b[a-1][1]?(b[a][1]=b[a-1][1]+b[a][1].substring(0,b[a][1].length-b[a-1][1].length),b[a+1][1]=b[a-1][1]+b[a+1][1],b.splice(a-1,1),d=q):b[a][1].substring(0,b[a+1][1].length)==b[a+1][1]&&(b[a-1][1]+=b[a+1][1],b[a][1]=b[a][1].substring(b[a+
1][1].length)+b[a+1][1],b.splice(a+1,1),d=q)),a++;d&&H(f,b)}w.prototype.h=function(f){for(var b=[],a=0;a<f.length;a++)switch(f[a][0]){case 1:b[a]="+"+encodeURI(f[a][1]);break;case -1:b[a]="-"+f[a][1].length;break;case 0:b[a]="="+f[a][1].length}return b.join("\t").replace(/%20/g," ")};
w.prototype.g=function(f,b){for(var a=[],d=0,h=0,c=b.split(/\t/g),e=0;e<c.length;e++){var g=c[e].substring(1);switch(c[e].charAt(0)){case "+":try{a[d++]=decodeURI(g)}catch(j){throw Error("Illegal escape in diff_fromDelta: "+g);}break;case "-":case "=":var k=parseInt(g,10);if(isNaN(k)||0>k)throw Error("Invalid number in diff_fromDelta: "+g);"-"==c[e].charAt(0)?h+=k:a[d++]=f.substring(h,h+=k);break;default:if(c[e])throw Error("Invalid diff operation in diff_fromDelta: "+c[e]);}}if(h!=f.length)throw Error("Delta length ("+
h+") does not equal source text length ("+f.length+").");return a.join("")};this.diff_match_patch=w;this.DIFF_DELETE=-1;this.DIFF_INSERT=1;this.DIFF_EQUAL=0;w.prototype.diff_main=w.prototype.a;w.prototype.diff_cleanupEfficiency=w.prototype.f;w.prototype.diff_toDelta=w.prototype.h;w.prototype.diff_fromDelta=w.prototype.g;