var mocha = {
  "describe": function () {},
  "it": function () {},
  "only": function () {},
  "eq": function () {},
  "not": {},
  "exist": {},
  "deep": {},
  "expect": function () {},
  "to": {},
  "be": {},
  "been": {},
  "is": {},
  "that": {},
  "and": {},
  "with": {},
  "have": {},
  "at": {},
  "of": {},
  "include": {},
  "itself": {},
  "ok": {},
  "undefined": {},
  "empty": {},
  "arguments": {},
  "above": {},
  "below": {},
  "least": {},
  "most": {},
  "within": {},
  "closeTo": {},
  "instanceof": {},
  "property": {},
  "ownProperty": {},
  "length": {},
  "match": {},
  "string": {},
  "keys": {},
  "throw": {},
  "respondTo": {},
  "satisfy": {},
  "create": {},
  "factory": {},
  "should": {}
};

var sinon = {
  "called": {},
  "calledOnce": {},
  "calledTwice": {},
  "calledThrice": {},
  "always": {},
  "calledWithNew": {},
  "calledBefore": {},
  "calledAfter": {},
  "calledOn": {},
  "calledWith": {},
  "calledWithExactly": {},
  "returned": {},
  "thrown": {},
  "spy": function () {}
};
