var mongodb = {
  "Db": {
    "open": function () {},
    "close": function () {},
    "db": function () {},
    "stats": function () {},
    "dropDatabase": function () {},
    "admin": function () {},
    "logout": function () {},
    "authenticate": function () {},
    "addUser": function () {},
    "removeUser": function () {},
    "collectionsInfo": function () {},
    "collectionNames": function () {},
    "collection": function () {},
    "collections": function () {},
    "createCollection": function () {},
    "dropCollection": function () {},
    "renameCollection": function () {},
    "eval": function () {},
    "dereference": function () {},
    "command": function () {},
    "lastError": function () {},
    "previousErrors": function () {},
    "resetErrorHistory": function () {},
    "createIndex": function () {},
    "ensureIndex": function () {},
    "dropIndex": function () {},
    "reIndex": function () {},
    "indexInformation": function () {}
  },
  "Cursor": {
    "PRIMARY": function () {},
    "SECONDARY": function () {},
    "PRIMARY_PREFERRED": function () {},
    "SECONDARY_PREFERRED": function () {},
    "NEAREST": function () {},
    "new": function () {},
    "each": function () {},
    "toArray": function () {},
    "nextObject": function () {},
    "rewind": function () {},
    "explain": function () {},
    "count": function () {},
    "close": function () {},
    "isClosed": function () {},
    "stream": function () {},
    "sort": function () {},
    "sort": function () {},
    "limit": function () {},
    "setReadPreference": function () {},
    "skip": function () {},
    "batchSize": function () {},
    "collection": function () {},
    "db": function () {},
    "selector": function () {},
    "fields": function () {}
  },
  "Collection": {
    "insert": function () {},
    "remove": function () {},
    "save": function () {},
    "update": function () {},
    "drop": function () {},
    "rename": function () {},
    "options": function () {},
    "isCapped": function () {},
    "stats": function () {},
    "distinct": function () {},
    "count": function () {},
    "findAndModify": function () {},
    "findAndRemove": function () {},
    "find": function () {},
    "findOne": function () {},
    "mapReduce": function () {},
    "group": function () {},
    "geoNear": function () {},
    "geoHaystackSearch": function () {},
    "aggregate": function () {},
    "createIndex": function () {},
    "ensureIndex": function () {},
    "indexInformation": function () {},
    "dropIndex": function () {},
    "dropAllIndexes": function () {},
    "reIndex": function () {},
    "indexExists": function () {},
    "indexes": function () {}
  },
  "Server": function () {}
};

global.module = {
  "exports": {}
};
