// Generated by CoffeeScript 1.6.2
(function() {
  var ObjectID;

  ObjectID = (function() {
    ObjectID.name = 'ObjectID';

    function ObjectID(hex) {
      var id;

      this.hex = hex;
      if (this.hex == null) {
        id = [];
        for (var i = 0; i < 24; ++i) id[i] = (Math.random()*16|0).toString(16);;
        this.hex = id.join('');
      }
    }

    ObjectID.prototype.toString = function() {
      return this.hex;
    };

    ObjectID.prototype['toJSON'] = function() {
      return this.hex;
    };

    return ObjectID;

  })();

  window['mongo'] = {
    'ObjectID': ObjectID
  };

}).call(this);
